theme: minima
title: Seah Ying Xiang | seahyx.github.io
email: seahyx@gmail.com
github_username: seahyx
description: HTML, CSS, JS, Flask, Flutter, Java, Python, C++, C#, Lua, Dart, and (My)SQL. I admit it, web dev makes me sick, but it's hella lit.
baseurl: '/'
url: 'localhost:4000'
google_site_verification: rcn0W-VkKUx63rQ2laiQ8rV2nbHcoeB8z0htPVaTmR4
plugins:
  - jekyll-seo-tag
